name: Graveyard
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'graveyard.json'
jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install yarn
      - name: Install dependencies
        run: yarn
      - name: Run Tests
        run: yarn run test
